name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2
      with:
       ref: ${{ github.event.pull_request.head.sha }}

    - name: Install cli-markdown
      run: npm i -g cli-markdown

    - name: Check Markdown
      run: md README.md

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
       node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run linters
      uses: wearerequired/lint-action@v2
      with:
        eslint: true
        prettier: true
        
    - name: Run tests
      run: npm run test:unit

    - name: Build
      run: npm run build

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: mariavasileva/hello-world:v1.0