name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Install cli-markdown
        run: npm i -g cli-markdown

      - name: Check Markdown
        run: md README.md

      - name: Run ESLint
        run: npx eslint .

      - name: Run Prettier
        run: npx prettier --check .

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test:unit

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mariavasileva/hello-world:${{ github.sha }}

      - name: Scan image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: "mariavasileva/hello-world:${{ github.sha }}"
          args: --severity-threshold=high
        continue-on-error: true
