name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install git-secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets
          make install

      - name: Run git-secrets
        run: |
          git secrets --add 'DOCKER_HUB_ACCESS_TOKEN'
          git secrets --scan

      - name: Install cli-markdown
        run: npm i -g cli-markdown

      - name: Check Markdown
        run: md README.md

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint .

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run tests
        run: npm run test:unit

      - name: Build
        run: npm run build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mariavasileva/hello-world:v1.0