name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter Release Branch Name (ex: 3.2 or 3.2.1)"
        required: true

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Branch
        run: |
          git checkout -b release/${{ github.event.inputs.version }}
          git push origin release/${{ github.event.inputs.version }}
